# Site
name: "CogSea"
title: "Cognitive Sea"
description: "We will walk you through the fabulous world of AI and <a href=\"/defining-knowledge/\">Knowledge</a>. Observe, Think, Act!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.ico'
baseurl: ''
google_analytics: 'G-KRS5PXWHYC'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
# email: wowthemesnet@gmail.com
main_twitter: https://twitter.com/GautiGauss
  
# Authors
authors:
  gaut:
    name: Gautier
    display_name: Gautier 
    avatar: 'assets/images/avatar.jpg'
    # email: wowthemesnet@gmail.com
    # web: https://www.wowthemes.net/donate/
    twitter: https://twitter.com/GautiGauss
    # instagram: https://www.instagram.com/gautigauss/
    description: "Economist, turned AI Engineer, 
    working for large and complex organisations, mainly in the financial sector, but not only.<br> 
    Passionate about Design and Collective Intelligence."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
# adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
